import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    useEffect(() => {
        window.location.href = window.location.href + '/' + 'login';
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.grid}></div>
            </main>
        </>
    );
}
